name: family_movie
description: A new Flutter project.

# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: "none" # Remove this line if you wish to publish to pub.dev


version: 1.0.0+1

environment:
  sdk: ">=2.18.6 <3.0.0"

dependencies:
  cached_network_image: ^3.2.3
  carousel_slider: ^4.2.0
  cupertino_icons: ^1.0.2
  dartz: ^0.10.1
  dio: ^4.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.0.2
  flutter_inappwebview: ^5.7.2+2
  flutter_localizations:
    sdk: flutter
  flutter_overlay_loader: ^2.0.0
  flutter_rating_bar: ^4.0.1
  flutter_svg: ^1.1.6
  flutter_svg_provider: ^1.0.3
  intl: ^0.17.0
  observable_ish: ^4.0.8
  pull_to_refresh: ^2.0.0
  shimmer: ^2.0.0
  stacked: ^3.0.1
  stacked_hooks: ^0.2.2
  stacked_services: ^0.9.8
  video_player: ^2.4.9
  youtube_player_flutter: ^8.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: ^2.3.2
  flutter_lints: ^2.0.0
  stacked_generator: ^0.8.1

flutter:
  uses-material-design: true
    assets:
    - assets/
    - assets/svg/
    - assets/images/
    - .env
  fonts:
    - family: Lato
      fonts:
        - asset: assets/fonts/Lato/Lato-Thin.ttf
          weight: 100
        - asset: assets/fonts/Lato/Lato-Light.ttf
          weight: 200
        - asset: assets/fonts/Lato/Lato-Regular.ttf
          weight: 300
        - asset: assets/fonts/Lato/Lato-Bold.ttf
          weight: 600
        - asset: assets/fonts/Lato/Lato-Black.ttf
          weight: 700
        - asset: assets/fonts/Lato/Lato-Italic.ttf
          style: italic
